# Generated by Django 4.2.1 on 2024-04-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_poll_stopped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='id_proof',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='id_proof',
        ),
    ]
